/**
 * SDK integration READMEs bundled as string constants.
 *
 * The imported file is generated by scripts/fetch-readmes.ts (run automatically
 * by scripts/build.ts before compilation) and gets bundled into the binary.
 *
 * To update locally: bun run scripts/fetch-readmes.ts
 */
import {
  README_REACT,
  README_BROWSER,
  README_NODE,
  README_REACT_NATIVE,
  README_ANGULAR,
  README_VUE,
  README_PYTHON,
  README_GO,
  README_RUBY,
  README_JAVA,
  README_DOTNET,
} from './readme-content.generated.js'

export function getReadmeContent(sdkPackage: string, framework: string): string {
  // Framework-specific overrides
  if (framework === 'angular') return README_ANGULAR
  if (framework === 'vue' || framework === 'nuxt') return README_VUE

  switch (sdkPackage) {
    case '@multiplayer-app/session-recorder-react':
      return README_REACT
    case '@multiplayer-app/session-recorder-react-native':
      return README_REACT_NATIVE
    case '@multiplayer-app/session-recorder-node':
      return README_NODE
    case '@multiplayer-app/session-recorder-browser':
      return README_BROWSER
    case 'multiplayer-python':
      return README_PYTHON
    case 'multiplayer-go':
      return README_GO
    case 'multiplayer-ruby':
      return README_RUBY
    case 'multiplayer-java':
      return README_JAVA
    case 'multiplayer-dotnet':
      return README_DOTNET
    default:
      return README_BROWSER
  }
}
