#!/usr/bin/env bun
/**
 * Fetches SDK integration READMEs from GitHub and generates
 * src/session-recorder/readme-content.generated.ts so they are bundled into
 * the compiled binary as string constants.
 *
 * Run manually: bun run scripts/fetch-readmes.ts
 * Run automatically: called by scripts/build.ts before compilation.
 */
import fs from 'fs'
import path from 'path'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT_FILE = path.join(ROOT, 'src', 'session-recorder', 'readme-content.generated.ts')

const JS_BASE =
  'https://raw.githubusercontent.com/multiplayer-app/multiplayer-session-recorder-javascript/main'

function ghRoot(repo: string) {
  return `https://raw.githubusercontent.com/multiplayer-app/${repo}/main/README.md`
}

const READMES: { name: string; url: string }[] = [
  // JavaScript monorepo
  { name: 'REACT', url: `${JS_BASE}/packages/session-recorder-react/README.md` },
  { name: 'BROWSER', url: `${JS_BASE}/packages/session-recorder-browser/README.md` },
  { name: 'NODE', url: `${JS_BASE}/packages/session-recorder-node/README.md` },
  { name: 'REACT_NATIVE', url: `${JS_BASE}/packages/session-recorder-react-native/README.md` },
  { name: 'ANGULAR', url: `${JS_BASE}/packages/session-recorder-browser/examples/angular/README.md` },
  { name: 'VUE', url: `${JS_BASE}/packages/session-recorder-browser/examples/vue/README.md` },
  // Per-language repos
  { name: 'PYTHON', url: ghRoot('multiplayer-session-recorder-python') },
  { name: 'GO', url: ghRoot('multiplayer-session-recorder-go') },
  { name: 'RUBY', url: ghRoot('multiplayer-session-recorder-ruby') },
  { name: 'JAVA', url: ghRoot('multiplayer-session-recorder-java') },
  { name: 'DOTNET', url: ghRoot('multiplayer-session-recorder-dotnet') },
]

const exports: string[] = ['// AUTO-GENERATED by scripts/fetch-readmes.ts — do not edit manually']
let ok = true

for (const { name, url } of READMES) {
  const res = await fetch(url)
  if (!res.ok) {
    console.error(`  ✗ ${name} (HTTP ${res.status}: ${url})`)
    ok = false
    continue
  }
  const content = await res.text()
  // Escape backticks and template literal syntax so the string literal is valid TS
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
  exports.push(`export const README_${name} = \`${escaped}\``)
  console.log(`  ✓ ${name}`)
}

if (!ok) process.exit(1)

fs.writeFileSync(OUT_FILE, exports.join('\n\n') + '\n')
